name: playwright
on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/package*.json"
      - "tests/**/*.spec.ts"
      - ".github/workflows/playwright.yml"
  workflow_dispatch:
    inputs:
      baseUrl:
        description: "Base URL for tests"
        required: true
        type: choice
        options:
          - "local"
          - "remote"
        default: "local"
  schedule:
    - cron: "0 21 1 * *"
env:
  NO_UPDATE_NOTIFIER: true
jobs:
  playwright:
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "tests/package-lock.json"
      - name: Install dependencies
        run: npm ci
        working-directory: ./tests
      - name: Cache playwright
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ${{ github.workspace }}/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('tests/package-lock.json') }}
      - name: Setup
        run: npm run playwright:setup
        working-directory: ./tests
      - name: Run tests (local)
        if: ${{ inputs.baseUrl == 'local' }}
        run: npm run playwright
        working-directory: ./tests
        env:
          CI: true
      - name: Run tests (remote)
        if: ${{ inputs.baseUrl != 'local'}}
        run: npm run playwright
        working-directory: ./tests
        env:
          CI: true
          BASE_URL: ${{ vars.URL }}
